version: 2.1
executors:
    node-executor:
        docker:
            - image cicrcleci/node:9.9
        working_directory: ~/webapp

jobs:
    install-dependencies:
        executor: node-executor
        working_directory: ~/webapp
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-

            - run: npm install

            - persist_to_webspace:
                root: ~/webapp
                paths:
                    - node_modules

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

    lint:
        execuor: node-executor
        working_directory: ~/webapp
        steps:
            - checkout
            - attach_workspace:
                at: ~/webapp
            - run: npm run lint

    test:
        executor: node-executor
        working_directory: ~/webapp
        steps:
            - checkout
            - attach_workspace:
                at: ~/webapp
            - run: npm test

workflows:
    version: 2
    github_pipeline:
        jobs:
            - install-dependencies
            - lint:
                 requires:
                     - install-dependencies
            - test:
                 requires:
                     - install-dependencies
